services:
  api:
    build: null
    image: ghcr.io/${GHCR_OWNER}/swcp-apigateway:${IMAGE_TAG}

  cloudllm:
    build: null
    image: ghcr.io/${GHCR_OWNER}/swcp-cloudllm:${IMAGE_TAG}

  db:
    build: null
    image: ghcr.io/${GHCR_OWNER}/swcp-postgres:${IMAGE_TAG}

  frontend:
    build: null
    image: ghcr.io/${GHCR_OWNER}/swcp-frontend:${IMAGE_TAG}
