sonar.organization=allankrogaau
sonar.projectKey=AllankrogAAU_SWCP_frontend
sonar.sources=src
sonar.test.inclusions=src/**/__tests__/**,src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true