sonar.organization=allankrogaau
sonar.projectKey=AllankrogAAU_SWCP_c-sandbox
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,**/*.c,**/*.h
sonar.test.exclusions=**/*.c,**/*.h
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true